### ISSUE TITLE
Task #2001 - Adicionar Novos Produtos

### ISSUE THREAD

**Issue by rvlyra** [rvlyra/dev-globalsys-01#2]
## Task #2001 - Adicionar nova lista de produtos

**Objetivo:** Modificar os tipos de produtos disponíveis e ajustar os valores, taxas de entrega e quaisquer outros cálculos relacionados.

**Tarefas:**

1. **Tipos de Produtos:** Modifique a lista de produtos disponíveis para representar um novo conjunto de produtos. Por exemplo, você pode escolher produtos eletrônicos, roupas ou alimentos.

2. **Valores e Taxas:** Defina preços diferentes para os novos produtos e ajuste as taxas de entrega se necessário. Certifique-se de atualizar os valores nas funções JavaScript para calcular o custo total com base nos novos produtos e taxas de entrega.

3. **Moeda Local:** Se você não está usando o Real brasileiro (R$), atualize a moeda e símbolos para refletir a moeda local usada em seu novo cenário. Por exemplo, use dólares (USD), euros (EUR) ou qualquer outra moeda.

4. **Compartilhe sua versão:** Após fazer as modificações, compartilhe o código HTML e JavaScript atualizado que representa o novo cenário de produtos e cálculos.

**Comment by GessicaGlobal** [comment]
Faltando acertar o somatorio final dos produtos com a entrega no codigo javascript pois a soma final atual está apresentando NaN.
